- name: Create SSH users on implusb2c-dev2-nfs if they don't exist
  hosts: implusb2c-dev2-nfs
  tasks:
    - name: Fetch user list from implusb2c-dev1-nfs
      include_tasks: fetch_users.yml

    - name: Create SSH users on implusb2c-dev2-nfs if they don't exist
      become: yes
      become_user: root
      user:
        name: "{{ item }}"
        shell: /bin/bash
        groups: www-data
        createhome: yes
      with_items: "{{ fetched_users }}"
      when: item not in ansible_users

    - name: Create .ssh directory for the users
      become: yes
      become_user: root
      file:
        path: "/home/{{ item }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ item }}"
        group: www-data
      with_items: "{{ fetched_users }}"
      when: item not in ansible_users

    - name: Set ownership for .ssh directory
      become: yes
      become_user: root
      file:
        path: "/home/{{ item }}/.ssh"
        state: directory
        owner: "{{ item }}"
        group: www-data
      with_items: "{{ fetched_users }}"
      when: item not in ansible_users

    - name: Copy authorized_keys file from implusb2c-dev1-nfs to implusb2c-dev2-nfs for each user
      copy:
        src: "/home/{{ item }}/.ssh/authorized_keys"
        dest: "/home/{{ item }}/.ssh/authorized_keys"
        mode: 0600
      with_items: "{{ fetched_users }}"
      when: item not in ansible_users
      delegate_to: implusb2c-dev1-nfs
      become: yes