---
- name: get user list
  hosts: implusb2c-dev2-nfs
  tasks:
    - name: Retrieve user list from implusb2c-dev1-nfs
      shell: ls -l /home | tail -n +2 | awk '{print $3}'
      register: users
      delegate_to: implusb2c-dev1-nfs
    - set_fact:
        fetched_users: "{{ users.stdout_lines }}"
    - name: Print fetched_users variable
      debug:
        var: fetched_users
    - name: Fetch existing user list from implusb2c-dev2-nfs
      command: ls -l /home | tail -n +2 | awk '{print $3}'
      register: existing_users
      delegate_to: implusb2c-dev2-nfs
    - set_fact:
        ansible_users: "{{ existing_users.stdout_lines }}"
    - name: Print ansible_users variable
      debug:
        var: ansible_users