---
- name: Fetch user list from implusb2c-dev1-nfs
  hosts: implusb2c-dev1-nfs
  gather_facts: false
  tasks:
    - name: Retrieve user list from implusb2c-dev1-nfs
      shell: ls -l /home | tail -n +2 | awk '{print $3}'
      register: users
      changed_when: false
    - set_fact:
        variable1: "{{ users.stdout_lines }}"
    - debug:
        var: variable1
- name: Fetch user list from implusb2c-dev2-nfs
  hosts: implusb2c-dev2-nfs
  gather_facts: false
  tasks:
    - name: Retrieve user list from implusb2c-dev2-nfs
      shell: ls -l /home | tail -n +2 | awk '{print $3}'
      register: users
      changed_when: false
    - set_fact:
        variable2: "{{ users.stdout_lines }}"
    - debug:
        var: variable1
